src/Entity/Sets.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SetsRepository")
 */
class Sets
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Pokemon", inversedBy="team")
     */
    private $pokemon;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Team", inversedBy="sets")
     * @ORM\JoinColumn(nullable=false)
     */
    private $team;

    /**
     * @ORM\Column(type="text")
     */
    private $paste;

    /**
     * @ORM\Column(type="string", length=40, nullable=true)
     */
    private $Item;

    /**
     * @ORM\Column(type="string", length=40)
     */
    private $Ability;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    private $Level;

    /**
     * @ORM\Column(type="string", length=3, nullable=true)
     */
    private $Happiness;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Evs;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $Nature;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $Ivs;

    /**
     * @ORM\Column(type="json")
     */
    private $Moves = [];

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getPokemon(): ?Pokemon
    {
        return $this->pokemon;
    }

    public function setPokemon(?Pokemon $pokemon): self
    {
        $this->pokemon = $pokemon;

        return $this;
    }

    public function getTeam(): ?Team
    {
        return $this->team;
    }

    public function setTeam(?Team $team): self
    {
        $this->team = $team;

        return $this;
    }

    public function getPaste(): ?string
    {
        return $this->paste;
    }

    public function setPaste(string $paste): self
    {
        $this->paste = $paste;

        return $this;
    }

    public function getItem(): ?string
    {
        return $this->Item;
    }

    public function setItem(?string $Item): self
    {
        $this->Item = $Item;

        return $this;
    }

    public function getAbility(): ?string
    {
        return $this->Ability;
    }

    public function setAbility(string $Ability): self
    {
        $this->Ability = $Ability;

        return $this;
    }

    public function getLevel(): ?string
    {
        return $this->Level;
    }

    public function setLevel(?string $Level): self
    {
        $this->Level = $Level;

        return $this;
    }

    public function getHappiness(): ?string
    {
        return $this->Happiness;
    }

    public function setHappiness(?string $Happiness): self
    {
        $this->Happiness = $Happiness;

        return $this;
    }

    public function getEvs(): ?string
    {
        return $this->Evs;
    }

    public function setEvs(string $Evs): self
    {
        $this->Evs = $Evs;

        return $this;
    }

    public function getNature(): ?string
    {
        return $this->Nature;
    }

    public function setNature(string $Nature): self
    {
        $this->Nature = $Nature;

        return $this;
    }

    public function getIvs(): ?string
    {
        return $this->Ivs;
    }

    public function setIvs(?string $Ivs): self
    {
        $this->Ivs = $Ivs;

        return $this;
    }

    public function getMoves(): ?array
    {
        return $this->Moves;
    }

    public function setMoves(array $Moves): self
    {
        $this->Moves = $Moves;

        return $this;
    }
}

src/Controller/MainController.php
<?php

namespace App\Controller;

use App\Data\searchTeam;
use App\Entity\Pokemon;
use App\Entity\Team;
use App\Form\SearchTeamType;
use App\Repository\TeamRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class MainController extends AbstractController
{
    /**
     * @Route("/", name="index")
     */
    public function index()
    {
        return $this->render('main/index.html.twig');
    }

    /**
     * @Route("/liste-des-equipes", name="search")
     * @param TeamRepository $repo
     * @return Response
     */
    public function search(TeamRepository $repo, Request $request)
    {
        // Classe qui récupèrera les infos du formulaire
       $data = new SearchTeam();

       // Formulaire des filtres de recherche
       $form = $this->createForm(SearchTeamType::class, $data);
       $form->handleRequest($request);


       $teamRepository = $this->getDoctrine()->getRepository(Team::class);

       $teams = $teamRepository->findTeam($data);

        return $this->render('main/search.html.twig', [
            'teams' => $teams,
            'form' => $form->createView()
        ]);
    }

    /**
     * @Route("/equipe-{id}", name="team", requirements={"id"="\d+"})
     * @param Team $team
     * @return Response
     */
    public function team(Team $team)
    {
        $teamOutput['name'] = $team->getName();
        $teamOutput['author'] = $team->getAuthor();
        $teamOutput['tier'] = $team->getTier();
        $teamOutput['sets'] = $team->getSets();

        return $this->render('main/team.html.twig',
            [
                'team' => $teamOutput,
            ]);
    }

}

templates/main/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Accueil{% endblock %}

{% block body %}

    {% for message in app.flashes('success') %}
        <div style="color:green;">{{ message }}</div>
    {% endfor %}


    <h1 class="page-title">Accueil</h1>
{% endblock %}

templates/main/search.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des équipes{% endblock %}

{% block body %}

        <div class="row">

            {# Sidebar filtres de recherche #}
            {# TODO: ajouter ce formulaire dans la page d'accueil et autres pages publiques #}
            <div class="col-12 col-md-3 searchteam-bar">

                {{ form_start(form, {attr: {class: 'searchteam-filter'}}) }}

                <h4>Nom de l'équipe :</h4>
                {{ form_row(form.q) }}

                <h4>Tier :</h4>
                {{ form_row(form.tiers) }}

                <h4>Contient :</h4>
                {{ form_row(form.pokemon) }}

                <button type="submit" class="btn btn-secondary">Rechercher</button>

                {{ form_end(form) }}

            </div>

            {# Affichage des teams #}
            <div class="col-12 col-md-9">
                <h1 class="page-title">Liste des équipes</h1>
                <div class="row">
                    {% for team in teams %}

                        <div class="team-display">
                            <a   href="{{ path('team', {'id' : team.id}) }}">
                                <h2 class="h3 d-block text-center team-name">{{ team.name }}</h2></a>
                            <div class="d-flex justify-content-between">


                                {% for set in team.sets %}

                                    {% if team.tier.getGeneration() > 6  %}
                                        <img class="sprite" src="{{ asset('img/Pokémon/ani/' ~ set.pokemon.name ~ '.gif') }}" alt="Image de {{ set.pokemon.name }}">
                                    {% else %}
                                        <img class="sprite" src="{{ asset('img/Pokémon/gen' ~ team.tier.getGeneration() ~ '/' ~ set.pokemon.name ~ '.png') }}" alt="Image de {{ set.pokemon.name }}">
                                    {% endif %}

                                {% endfor %}
                            </div>
                            <div class="team-info row justify-content-between">
                                <p class="d-block">Par : <a href="#"><small class="team-author">{{ team.author.email }}</small></a></p>
                                <a href="{{ path('search', {'tiers' : team.tier.id}) }}">
                                    <div class="tier-magnet gen-{{ team.tier.generation }}">
                                    <p class="m-0">{{ team.tier.generation }}G {{ team.tier.name }}</p>
                                    </div>
                                </a>
                            </div>
                        </div>

                    {% endfor %}

                </div>
            </div>
        </div>


{% endblock %}

{% block javascript %}

<script src="{{ asset('js/searchteam-filter.js') }}"></script>

{% endblock %}

templates/main/team.html.twig
{% extends 'base.html.twig' %}

{% block title %}Team{% endblock %}

{% block body %}
    <h1 class="page-title">[GEN {{ team.tier.getGeneration }} ] {{ team.tier.getName }} - {{ team.name }}</h1>
    <div class="row mx-5 mx-sm-0 justify-content-center d-flex">

        {% for set in team.sets  %}

            <div class="col-12 col-sm-4 col-md-3 pokemon-info">

                <div class="d-flex align-items-center flex-column">
                    {% if team.tier.getGeneration > 6  %}
                        <img class="sprite" src="{{ asset('img/Pokémon/ani/' ~ set.pokemon.name ~ '.gif') }}" alt="Image de {{ set.pokemon.name }}">
                    {% else %}
                        <img class="sprite" src="{{ asset('img/Pokémon/gen' ~ team.tier.getGeneration ~ '/' ~ set.pokemon.name ~ '.png') }}" alt="Image de {{ set.pokemon.name }}">
                    {% endif %}

                    <div>
                        <img src="{{ asset('img/Pokémon/types/' ~ set.pokemon.type1 ~ '.png') }}" alt="Image du type {{ set.pokemon.type1 }}">
                        {% if set.pokemon.type2 is not null %}
                            <img src="{{ asset('img/Pokémon/types/' ~ set.pokemon.type2 ~ '.png') }}" alt="Image du type {{ set.pokemon.type2 }}">
                        {% endif %}
                    </div>

                    <h2 class="text-center">{{ set.pokemon.name|capitalize }}</h2>

                </div>


                <div class="set-details">

                    {% if set.item is not empty %}
                        <p class="h6">@ {{ set.item }}</p>
                    {% endif %}

                    <p class="h6">Talent :  {{ set.ability }}</p>
                    <p class="h6">Nature : {{ set.nature }}</p>

                    {% if set.evs is not empty %}
                        <p class="h6">EVs : {{ set.evs }}</p>
                    {% endif %}

                    {% if set.ivs is not empty %}
                        <p class="h6">iVs : {{ set.ivs }}</p>
                    {% endif %}
                </div>

                <div class="pokemon-moves">
                        <ul>
                            {% for move in set.moves %}
                                {# TODO: trouver un svg pour remplacer les ul decoration #}
                                <li>- {{ move }}</li>
                            {% endfor %}
                        </ul>
                    </div>

            </div>

        {% endfor %}

    </div>
{% endblock %}